apiVersion: v2
name: traefik-hub
description: Traefik Hub Ingress Controller
type: application
version: 3.0.0
# renovate: image=ghcr.io/traefik/traefik-hub
appVersion: v2.8.0
kubeVersion: ">=1.24.0-0"
keywords:
  - traefik
  - ingress
  - networking
  - api
  - apimanagement
home: https://traefik.io/traefik-hub
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: mmatur
    email: michael.matur@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
icon: https://doc.traefik.io/traefik-hub/assets/images/logos-traefik-hub-horizontal.svg
annotations:
  artifacthub.io/changes: |
    - "fix!: use release name for resources name"
    - "fix!: IngressClass should not be created by default"
    - "fix: remove unnecessary rbac"
    - "chore: upgrade traefik-hub version"
    - "chore: update CRDs"
    - "chore: remove unnecessary env var"
